
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb-typescript/base'

settings:
  react:
    version: 'detect'
  settings":
    'import/resolver':
      node: { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true

  ecmaVersion: 2020
  sourceType: 'module'
  project: './tsconfig.eslint.json'

plugins: ['react', '@typescript-eslint']
ignorePatterns: ['node_modules', 'dist', 'babel.config.js']
rules:
  'import/no-extraneous-dependencies': ['error', { devDependencies: true }]
  '@typescript-eslint/no-var-requires': 0
  'import/extensions': 'off'